module "vpc" {
  source                   = "git::https://github.com/tonygyerr/terraform-aws-vpc.git"
  app_name                   = var.app_name
  azs                        = var.azs
  cidr                       = var.vpc_cidr
  public_subnets             = var.public_subnets
  private_subnets            = var.private_subnets
  db_prv_subnets             = var.db_prv_subnets
  elasticache_prv_subnets    = var.elasticache_prv_subnets
  amount_public_subnets      = var.amount_public_subnets
  amount_private_subnets     = var.amount_private_subnets
  amount_private_db_subnets  = var.amount_private_db_subnets
  amount_elasticache_subnets = var.amount_elasticache_subnets
  enable_dynamodb_endpoint   = true
  enable_nat_gateway         = true
  enable_s3_endpoint         = true
  enable_vpn_gateway         = true
  environment                = var.environment
  module_config              = var.module_config
  region                     = var.aws_region
  single_nat_gateway         = true
  vpc_config                 = var.vpc_config
  vpc_id                     = module.vpc.vpc_id
  vpn_config                 = var.vpn_config
  vpn_ip_address             = var.vpn_ip_address
}