module "vpc" {
  source                   = "git::ssh://git@github.com:tonygyerr/terraform-aws-vpc.git"
  app_name                 = var.app_name
  azs                      = var.azs
  cidr                     = var.vpc_cidr
  api_prv_subnets          = var.api_prv_subnets
  api_pub_subnets          = var.api_pub_subnets
  db_prv_subnets           = var.db_prv_subnets
  lb_prv_subnets           = var.lb_prv_subnets
  private_db_subnet_ids    = module.vpc.private_db_subnets
  private_subnets          = var.private_subnets
  enable_dynamodb_endpoint = true
  enable_nat_gateway       = true
  enable_s3_endpoint       = true
  enable_vpn_gateway       = true
  environment              = var.environment
  module_config            = var.module_config
  region                   = var.aws_region
  single_nat_gateway       = true
  vpc_config               = var.vpc_config
  vpc_id                   = module.vpc.vpc_id
  vpn_config               = var.vpn_config
  vpn_ip_address           = var.vpn_ip_address
}